version: '3.8'

services:
  tnetc-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # Run as root for debugging issues with data directory
    user: "root"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 